const express=require("express")
const SigningController=require("../controller/login")
const UserDetail=require("../controller/userDetail")
const Authtoken=require("../middleware/authmiddleware")
const userLogout=require("../controller/UserLogOut")
const AllUser=require("../controller/AllUsers")
const updateUser=require("../controller/UpdateUser")
const uploadProduct=require("../controller/UploadProduct")
const allProducts=require("../controller/GetAllProduct")
const allCatagoryProducts=require("../controller/GetAllCatagoryProduct")
const CatagoryWiseProduct=require("../controller/CatagorywiseProducts")
const productDetails=require("../controller/productDetailsById")
const addToCartProduct=require("../controller/AddToCart")
const countCartProduct=require("../controller/CountCartProduct")
const cartProductview=require("../controller/AddToCartView")
const router =express.Router()

router.post("/api/login" , SigningController.login)
router.post("/api/signup" , SigningController.signup)
router.get("/api/userDetail" , Authtoken ,UserDetail)
router.get("/api/userLogOut" ,userLogout)
router.get("/api/allUser" ,Authtoken,  AllUser)
router.post('/api/usersUpdate', Authtoken,  updateUser);
router.post("/api/uploadProduct" , uploadProduct)
router.get("/api/getAllProducts" , allProducts)
router.get("/api/getAllCatagoryProduct" , allCatagoryProducts )
router.post("/api/catagoryWiseProduct" , CatagoryWiseProduct)
router.post("/api/productDetails" , productDetails)
router.post("/api/addToCartProduct" ,Authtoken , addToCartProduct )
router.get("/api/countProductItems" , Authtoken , countCartProduct)
router.get("/api/cartProductview" , Authtoken ,cartProductview  )

module.exports=router